version: '3.8'

services:
  readability-api:
    build: .
    container_name: readability-api
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    environment:
      - PORT=${PORT:-3000}
      - API_TOKEN=${API_TOKEN}
      - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-900000}
      - RATE_LIMIT_MAX=${RATE_LIMIT_MAX:-100}
      - AXIOS_TIMEOUT=${AXIOS_TIMEOUT:-10000}
    restart: unless-stopped
    volumes:
      - ./logs:/usr/src/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:${PORT:-3000}/api/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s 